name: Deploy action on Heroku

on:
  push:
    branches:
      - khanh_heroku

jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm test
  deploy:
    needs: unit_testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "herokuadvanced-mongo" #Must be unique in Heroku
          heroku_email: "khanhqhoang@hotmail.com"